[workspace]
members = [
    "programs/reward_pump",
]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1